version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka1:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - ./config/kafka1.properties:/etc/kafka/server.properties
    command: ["sh", "-c", "exec kafka-server-start /etc/kafka/server.properties"]

  kafka2:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka2
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    volumes:
      - ./config/kafka2.properties:/etc/kafka/server.properties
    command: ["sh", "-c", "exec kafka-server-start /etc/kafka/server.properties"]

  kafka3:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka3
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    volumes:
      - ./config/kafka3.properties:/etc/kafka/server.properties
    command: ["sh", "-c", "exec kafka-server-start /etc/kafka/server.properties"]
